In [65]:
import pandas as pd
df = pd.read_csv("analytics_device.csv")
df.head()

,Date,HgAd1-Close1-Hg2.5,HgAd8-Close2-Hg2.5,HgAd5-Close1-Hg2.5,HgAd7-Far1-Hg2.5,Player_Bought_Spider_Jump,HgAd8-Far05-Hg2.5,HgAd1-Far1-Hg2.5,HgAd6-Far1-Hg2.5,HgAd-Player_Joined-Hg2.5,...,SniperElim,ShotgunElim,HgAd1-Close05-Hg2.5,HgAd3-Medium2-Hg2.5,Player_Bought_Instant_Reload,HgAd6-Medium1-Hg2.5,HgAd5-Medium05-Hg2.5,HgAd2-Medium2-Hg2.5,HgAd5-Close2-Hg2.5,HgAd7-Medium05-Hg2.5
0,2025-02-27,737,775,580,"61,122","1,194","76,445","54,455","1,359","8,175",...,"13,201","22,243",588,"17,041",709,"10,856","9,115","1,259",492,"31,330"

In [66]:
df.columns

Index(['Date', 'HgAd1-Close1-Hg2.5', 'HgAd8-Close2-Hg2.5',
       'HgAd5-Close1-Hg2.5', 'HgAd7-Far1-Hg2.5', 'Player_Bought_Spider_Jump',
       'HgAd8-Far05-Hg2.5', 'HgAd1-Far1-Hg2.5', 'HgAd6-Far1-Hg2.5',
       'HgAd-Player_Joined-Hg2.5', 'HgAd4-Far2-Hg2.5', 'HgAd8-Medium2-Hg2.5',
       'HgAd2-Close1-Hg2.5', 'HgAd5-Close05-Hg2.5', 'HgAd7-Far05-Hg2.5',
       'HgAd1-Far05-Hg2.5', 'HgAd3-Close2-Hg2.5', 'HgAd1-Close2-Hg2.5',
       'AirstrikeCode', 'ZappotronCode', 'Player_Bought_Double_HP',
       'HgAd4-Medium05-Hg2.5', 'HgAd-Purple_Team_Joined-Hg2.5',
       'HgAd6-Far05-Hg2.5', 'HgAd4-Close05-Hg2.5', 'HgAd3-Far05-Hg2.5',
       'Headshot', 'HgAd4-Medium1-Hg2.5', 'HgAd1-Medium05-Hg2.5',
       'HgAd5-Medium1-Hg2.5', 'HgAd2-Close05-Hg2.5', 'HgAd2-Far1-Hg2.5',
       'ZeusThunderbolt', 'PlasmaCannonCode', 'HgAd7-Close1-Hg2.5',
       'HgAd1-Medium2-Hg2.5', 'HgAd7-Medium1-Hg2.5', 'HgAd2-Far2-Hg2.5',
       'Elmination', 'HgAd6-Close05-Hg2.5', 'HgAd4-Far1-Hg2.5',
       'HgAd8-Medium1-Hg2.5', 'HgAd1-Medium1-Hg2.5', 'InfinityBladeCode',
       'HgAd3-Far1-Hg2.5', 'HgAd6-Far2-Hg2.5', 'HgAd4-Medium2-Hg2.5',
       'HgAd2-Medium05-Hg2.5', 'HgAd8-Close05-Hg2.5', 'HgAd5-Far2-Hg2.5',
       'HgAd3-Medium05-Hg2.5', 'HgAd2-Medium1-Hg2.5', 'HgAd2-Close2-Hg2.5',
       'Player_Joined', 'HgAd3-Medium1-Hg2.5', 'HgAd1-Far2-Hg2.5',
       'Player_Bought_Double_Pump', 'HgAd5-Far1-Hg2.5', 'HgAd7-Close05-Hg2.5',
       'HgAd3-Far2-Hg2.5', 'HgAd6-Close2-Hg2.5', 'SMGElim',
       'HgAd5-Medium2-Hg2.5', 'HgAd7-Close2-Hg2.5', 'HgAd6-Medium2-Hg2.5',
       'HgAd3-Close05-Hg2.5', 'HgAd8-Far2-Hg2.5', 'HgAd4-Close2-Hg2.5',
       'HgAd7-Medium2-Hg2.5', 'HgAd6-Medium05-Hg2.5',
       'HgAd-Green_Team_Joined-Hg2.5', 'HgAd4-Close1-Hg2.5',
       'HgAd8-Close1-Hg2.5', 'HgAd8-Far1-Hg2.5', 'HgAd7-Far2-Hg2.5', 'ARElim',
       'HgAd3-Close1-Hg2.5', 'HgAd4-Far05-Hg2.5', 'Player_Bought_Invisibility',
       'HgAd6-Close1-Hg2.5', 'HgAd2-Far05-Hg2.5', 'HgAd8-Medium05-Hg2.5',
       'HgAd5-Far05-Hg2.5', 'SniperElim', 'ShotgunElim', 'HgAd1-Close05-Hg2.5',
       'HgAd3-Medium2-Hg2.5', 'Player_Bought_Instant_Reload',
       'HgAd6-Medium1-Hg2.5', 'HgAd5-Medium05-Hg2.5', 'HgAd2-Medium2-Hg2.5',
       'HgAd5-Close2-Hg2.5', 'HgAd7-Medium05-Hg2.5'],
      dtype='object')

In [67]:
ad_to_column = {}
ads = ['Ad1', 'Ad2', 'Ad3', 'Ad4', 'Ad5', 'Ad6', 'Ad7', 'Ad8']
for c in df.columns:
    ad = c[2:5]
    if ad in ads and ad in ad_to_column:
        tag = c[6:]
        ad_to_column[ad].append((tag, df[c][0]))
    elif ad in ads and not ad in ad_to_column:
        tag = c[6:]
        ad_to_column[ad] = [(tag, df[c][0])]

In [68]:
print(ad_to_column)

{'Ad1': [('Close1-Hg2.5', np.int64(737)), ('Far1-Hg2.5', '54,455'), ('Far05-Hg2.5', '61,796'), ('Close2-Hg2.5', '1,327'), ('Medium05-Hg2.5', '7,596'), ('Medium2-Hg2.5', '7,214'), ('Medium1-Hg2.5', '7,487'), ('Far2-Hg2.5', '60,390'), ('Close05-Hg2.5', np.int64(588))], 'Ad8': [('Close2-Hg2.5', np.int64(775)), ('Far05-Hg2.5', '76,445'), ('Medium2-Hg2.5', '18,890'), ('Medium1-Hg2.5', '20,396'), ('Close05-Hg2.5', np.int64(531)), ('Far2-Hg2.5', '85,023'), ('Close1-Hg2.5', np.int64(713)), ('Far1-Hg2.5', '69,155'), ('Medium05-Hg2.5', '22,121')], 'Ad5': [('Close1-Hg2.5', np.int64(580)), ('Close05-Hg2.5', np.int64(485)), ('Medium1-Hg2.5', '7,271'), ('Far2-Hg2.5', '2,851'), ('Far1-Hg2.5', '1,538'), ('Medium2-Hg2.5', '9,324'), ('Far05-Hg2.5', '1,238'), ('Medium05-Hg2.5', '9,115'), ('Close2-Hg2.5', np.int64(492))], 'Ad7': [('Far1-Hg2.5', '61,122'), ('Far05-Hg2.5', '68,207'), ('Close1-Hg2.5', '1,162'), ('Medium1-Hg2.5', '26,319'), ('Close05-Hg2.5', np.int64(866)), ('Close2-Hg2.5', '1,433'), ('Medium2-Hg2.5', '22,720'), ('Far2-Hg2.5', '74,349'), ('Medium05-Hg2.5', '31,330')], 'Ad6': [('Far1-Hg2.5', '1,359'), ('Far05-Hg2.5', '1,113'), ('Close05-Hg2.5', np.int64(566)), ('Far2-Hg2.5', '3,515'), ('Close2-Hg2.5', np.int64(620)), ('Medium2-Hg2.5', '15,734'), ('Medium05-Hg2.5', '12,243'), ('Close1-Hg2.5', np.int64(697)), ('Medium1-Hg2.5', '10,856')], 'Ad4': [('Far2-Hg2.5', '8,253'), ('Medium05-Hg2.5', '2,789'), ('Close05-Hg2.5', np.int64(825)), ('Medium1-Hg2.5', '2,642'), ('Far1-Hg2.5', '5,682'), ('Medium2-Hg2.5', '2,844'), ('Close2-Hg2.5', np.int64(723)), ('Close1-Hg2.5', np.int64(918)), ('Far05-Hg2.5', '5,815')], 'Ad2': [('Close1-Hg2.5', np.int64(323)), ('Close05-Hg2.5', np.int64(275)), ('Far1-Hg2.5', np.int64(617)), ('Far2-Hg2.5', '1,132'), ('Medium05-Hg2.5', '1,452'), ('Medium1-Hg2.5', '1,177'), ('Close2-Hg2.5', np.int64(281)), ('Far05-Hg2.5', np.int64(526)), ('Medium2-Hg2.5', '1,259')], 'Ad3': [('Close2-Hg2.5', np.int64(803)), ('Far05-Hg2.5', '71,943'), ('Far1-Hg2.5', '65,563'), ('Medium05-Hg2.5', '23,447'), ('Medium1-Hg2.5', '20,443'), ('Far2-Hg2.5', '83,942'), ('Close05-Hg2.5', np.int64(542)), ('Close1-Hg2.5', np.int64(739)), ('Medium2-Hg2.5', '17,041')]}

In [69]:
df = pd.DataFrame.from_dict({k: dict(v) for k, v in ad_to_column.items()}, orient='index')

# Convert all values to numeric (handling commas)
df = df.applymap(lambda x: pd.to_numeric(str(x).replace(',', ''), errors='coerce'))

# Define groups based on column names
close_cols = [col for col in df.columns if 'Close' in col]
medium_cols = [col for col in df.columns if 'Medium' in col]
far_cols = [col for col in df.columns if 'Far' in col]

# Create accumulative columns
df['Close Accumulative'] = df[close_cols].sum(axis=1)
df['Medium Accumulative'] = df[medium_cols].sum(axis=1)
df['Far Accumulative'] = df[far_cols].sum(axis=1)
df['Overall Accumulative'] = df.sum(axis=1)

/var/folders/vc/bt9dsj751rq6hfqjs96kc0f00000gp/T/ipykernel_71266/661756709.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: pd.to_numeric(str(x).replace(',', ''), errors='coerce'))

In [70]:
df = df.reindex(sorted(df.columns), axis=1)
df = df.sort_index()

In [71]:
df.head(10)

,Close Accumulative,Close05-Hg2.5,Close1-Hg2.5,Close2-Hg2.5,Far Accumulative,Far05-Hg2.5,Far1-Hg2.5,Far2-Hg2.5,Medium Accumulative,Medium05-Hg2.5,Medium1-Hg2.5,Medium2-Hg2.5,Overall Accumulative
Ad1,2652,588,737,1327,176641,61796,54455,60390,22297,7596,7487,7214,403180
Ad2,879,275,323,281,2275,526,617,1132,3888,1452,1177,1259,14084
Ad3,2084,542,739,803,221448,71943,65563,83942,60931,23447,20443,17041,568926
Ad4,2466,825,918,723,19750,5815,5682,8253,8275,2789,2642,2844,60982
Ad5,1557,485,580,492,5627,1238,1538,2851,25710,9115,7271,9324,65788
Ad6,1883,566,697,620,5987,1113,1359,3515,38833,12243,10856,15734,93406
Ad7,3461,866,1162,1433,203678,68207,61122,74349,80369,31330,26319,22720,575016
Ad8,2019,531,713,775,230623,76445,69155,85023,61407,22121,20396,18890,588098